### ISSUE TITLE
Ingestion request: NEJLT vol 7 & 8

### ISSUE THREAD

**Issue by leondz** [acl-org/acl-anthology#2336]
This is a new (to the anthology) venue.

* **Venue name:** Northern European Journal of Language Technology (NEJLT)
* **Website:** [nejlt.org](https://www.nejlt.org/)
* Papers at https://doi.org/10.3384/nejlt.2000-1533.8.1 and https://doi.org/10.3384/nejlt.2000-1533.7.1

I propose:
* volume identifier `nejlt`
* volume titles in the format _Northern European Journal of Language Technology, Volume n_

We're ready to send over two volumes, for 2021 and 2022. Iff and when this is OK with you, I'm happy to go assemble ACLPUB format volumes and send them.

**Comment by mjpost** [comment]
Looks good to me. I suggest starting with one volume to get the details right, then we can move to the next. @xinru1414 can process when you're ready.

**Comment by leondz** [comment]
Alright, here's a first pass :)

> [nejlt_2021_data.tgz](https://github.com/acl-org/acl-anthology/files/10407895/nejlt_2021_data.tgz)


It's best effort - I got this, sorry if I've found the wrong version somehow (followed https://acl-org.github.io/ACLPUB/anthology.html).
```
leod@mac622226 nejlt-pub % python3 ACLPUB/bin/sanity_check.py data
This script doesn't do anything yet. So you're all good!
```

**Comment by leondz** [comment]
@xinru1414 Is there anything more I can do to help on this?

**Comment by leondz** [comment]
@xinru1414 This was a short issue, so no front matter or full proceedings was compiled. I've seen prior items on the anthology without them, but maybe that's no longer the policy - happy to build these if requested.

**Comment by leondz** [comment]
@xinru1414 @mjpost  Do you require these for a 2-paper issue? Please let me know.

**Comment by mbollmann** [comment]
@mjpost I suspect #2379 and d8a9e0f2c2ac2ae3b1a9f72bb8f0819cd16bbb01 is relevant for this as well.

**Comment by mjpost** [comment]
Sorry @leondz I had forgotten you already filed this. @xinru1414 let's just import as-is?

**Comment by mjpost** [comment]
@xinru1414 Please ingest on the #nejlt branch (#2399) where I've created the stub for handling the code. We need to merge this after TAL.

**Comment by xinru1414** [comment]
@leondz please pass on Vol 8 as well!

**Comment by mjpost** [comment]
Yes, @leondz, also the Vol. 7 preview is ready if you can have a look: https://preview.aclanthology.org/nejlt/volumes/2021.nejlt-1/

**Comment by nschneid** [comment]
Thanks—is Edinburgh, UK correct as the location?

**Comment by nschneid** [comment]
And should the publisher be ACL or Linköping University Electronic Press?

**Comment by leondz** [comment]
* Mostly looks good
* Volume DOI is missing, https://doi.org/10.3384/nejlt.2000-1533.7.1 . Where should this go? Is `doi` a `meta` field undocumented in the [ACLPUB docs](https://acl-org.github.io/ACLPUB/anthology.html) ?
* The location is indeed incorrect; the `location` specified in the `meta` file is Copenhagen, Denmark. Is this the right field name? I followed these [docs](https://acl-org.github.io/ACLPUB/anthology.html)
* Two publishers were specified in the `meta` file, looks like only the first was picked up. I don't have a strong preference for which is listed here; ostensibly a third value, the Northern European Association for Language Technology, is _also_ a valid value.

**Comment by leondz** [comment]
Follow-up re: publisher - I think I'd definitely like to amend this from how it currently appears, what's the best way to do that? Rebuild the aclpub tgz and attach it - here?

**Comment by xinru1414** [comment]
@mjpost 
- I think DOI ingestion is a separate process? 
- I've only seen one publisher, do we allow multiple publishers? I manually selected ACL as the publisher.

@leondz 
- I've corrected the location

**Comment by mjpost** [comment]
We normally apply DOI ourselves but only for ACL events. If they exist already it should be read in with the paper metadata if it's in the bibtex. 

I think bib only supports one publisher? Can you tell us what values to use? We could combine them into one I suppose. No need to reingest we can just edit manually but please correct for the future.

**Comment by xinru1414** [comment]
DOI info is in the bib file, I'll ingest. @leondz please confirm the publisher and also Vol 8 material.

**Comment by leondz** [comment]
Great! For publisher, "Northern European Association of Language Technology" is the best value, sorry about the change.

I've automated volume-to-ACLPUB for us now. I'm still not sure about:

* Where to specify volume-level DOIs, so e.g. the DOI field on https://preview.aclanthology.org/nejlt/volumes/2021.nejlt-1/ is populated not with `-` but with `https://doi.org/10.3384/nejlt.2000-1533.7.1`. It sounds like perhaps fixing this manually post-hoc might be the best route, in the event there's no code to read it from ACLPUB packages.
* What field to use in `meta` in order to communicate the location correctly, if not `location`

Vol 8 material is all done but now a designer is going to send us a front cover, so this might not be til early next week. I have a (traditionally) ugly one as backup.

**Comment by xinru1414** [comment]
@leondz 
- I agree, adding volume level DOI manually is the best choice. I've added the info for 2021.
- Location field is the correct field.
- We can wait on vol 8.

**Comment by leondz** [comment]
Thanks!

-- by the way - can abstracts go in the bib or is draft aclpub2 required for this?

**Comment by xinru1414** [comment]
@leondz aclpub2 is not required.

**Comment by leondz** [comment]
Great. 

Here's the [acl tgz for NEJLT issue 8](www.derczynski.com/nejlt_2022_data.tgz)

I also now have a combined PDF incl. front matter for NEJLT issue 7, attached: [nejlt-2021.1.pdf](https://github.com/acl-org/acl-anthology/files/10843755/nejlt-2021.1.pdf)

**Comment by xinru1414** [comment]
@leondz issue 8 link is invalid.

**Comment by leondz** [comment]
Oh right, http:// prefix added now, tested + working

**Comment by leondz** [comment]
Was there a bib validation issue with `2022.nejlt-1.4`- `2022.nejlt-1.9`? See https://preview.aclanthology.org/nejlt/volumes/2022.nejlt-1/, where bib links are missing for these items

**Comment by mjpost** [comment]
We don't generate all bibs on previews (and the links are broken on the ones we do). It creates too many files and slows down the system.

https://preview.aclanthology.org/nejlt/2022.nejlt-1.3.bib looks good.

**Comment by evanmiltenburg** [comment]
General question as a curious NEJLT author: will papers that appear in NEJLT be published in the Anthology as they are published online, or will they be published in batches? (e.g. every year all papers from that year are added)

I think the former option is preferable for authors (since otherwise there is an average delay of 6 months before papers appear in the Anthology), but I am not sure if the system is set up for this kind of incremental publishing.

**Comment by mjpost** [comment]
We can ingest as often as they're given to use. We do TACL/CL on a bimonthly basis for example.

**Comment by leondz** [comment]
From the NEJLT side, packaging issues for ingestion is now one single command, so we can send updates as rapidly as the Anthology can take them.

**Comment by xinru1414** [comment]
If the ingestion material is ready, feel free to open an ingestion request at any time. They'll be processed in a timely manner.

**Comment by evanmiltenburg** [comment]
Good to hear! Well done making this work :)
