### ISSUE TITLE
ACL IDs—looking forward

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#291]
We currently issue ACL IDs in the following format:

    IYY-VXXX
    IYY-VVXX

where

- `I` is the ACL identifier
- `YY` is the year
- `V` or `VV` is the volume identifier
- `XXX` or `XX` is the paper identifier

I like this format quite a bit and am loathe to part with it, but sooner, rather than later, it is going to cause problems. Potential ones are:

- There can be only 99 workshops, and each workshop can have only 99 papers (since 00 is reserved for the front matter). This is already a problem with WMT, only avoided by creating separate workshop volume IDs for research and system description papers.
- There can be only 9 (or 10?) volumes in a single year. This hasn't been a problem but could be.
- There can be only 999 papers in a single volume. Maybe the AI bubble will pop and we won't have to worry about this.
- We are going to have a headache in about 55 years when the two digit year cycles over (or sooner, if we find and ingest any earlier documents).

We should find a more general format. Please let me know your thoughts.

One thing we could

**Comment by mbollmann** [comment]
First of all—the [information page for contributors](https://aclweb.org/anthology/info/contrib/) says:

> The file names fit within the 8.3 DOS naming constraint for maximum portability, as recommended by Adobe.

Going forward, I assume we'll have to give up this principle; but I'd also be surprised if it was still as relevant today.

- - -

Some thoughts:

1. Most of the problems go away if we introduce an explicit separator between volume and paper identifier, as that allows us to make the identifiers any length we want; e.g., `W55-147-0008`.

2. Alternatively, volume identifiers could become a fixed number of letters. Either two to keep it short (which allows for at least 26²=626 volumes), or three to make them more semantic. For example, the 40th edition of the RepL4NLP workshop could have the identifiers `W55-REPxxxx`.

3. The year problem is most obviously solved by giving the full year instead, though I'll admit I find `W2055-vxxx` rather ugly. Maybe we can make do with three characters for the year (`W055-`)?

**Comment by aryamccarthy** [comment]
If we're going to fix it, 2020 is round, so it's the best-looking year for awhile. It'll help people remember "Should I use the old-style ID or new-style ID?"

I'm a fan of @mbollmann's options 1 and 3. (There may be a scramble for the best 3-letter codes in option 2.)

---

How close are we getting to any of these limits—99 workshops, 9 volumes, 999 papers? Is there an avenue for re-using the first-letter identifiers? We seem to have [doled out most of them](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/venues_letters.yaml) already.

**Comment by knmnyn** [comment]
Hi all:

As I recall we still have a few letter prefixes left.  We could also
sanction another letter for extending the workshop line, but I think since
you are all trying to revamp the system, that is not a good idea.

I vote for full yyyy identification just to be safe about it.

We moved to using acronym slugs in search and front page to lessen the need
and burden of having the ACL ID to be a transparent identifier.  The hope
was to use the search and access stats to promote a usage-based UI for
presenting the ordering of the venues (e.g., WMT might get better billing
than ROCLING, even though the latter has its own lettered prefix).

**Comment by leondz** [comment]
Full yyyy makes a lot of sense. The 8.3 restriction doesn't seem very applicable now (even NT 3.5 in 1994, and DOS 7.1, supported long filenames in under FAT - that's a quarter of a century back!). Making a longer filename lets us have more description in the name. That said, I do enjoy being able to give a code in the current format and have other ACLers know that it refers to a paper, and sometimes even the venue and format.

It would help to have some idea for when other letters can be assigned. This might give a better use of the available filename coding space.

The limit of 9 volumes per year (10? Is zero allowed) and 999 items per volume could be worked around with an offset use to double the available space, or allocating >1 volume per logical volume. in a similar way to UK numberplates, where for these, a new registration prefix is issued every six months, with the second in the cycle getting +50. For example, OD19 would be a car registered in Exeter in the first half of 2019, OD69 for one registered Autumn or later. Similarly, volume 6 could be by default an extension of volume 1, and so on. So we might survive even if the bubble doesn't pop.

2020 seems a great year for rolling over.

But in short, I think - especially for newcomers - it's OK to transition to e.g. ACL2020-100001 for the first long paper that year.

**Comment by mjpost** [comment]
It would also be nice to move away from single-letter identifiers (which require the user to memorize the mapping) to something more meaningful. We could create a single unique identifier for every conference, workshop, or journal---we actually already have this in [venues.yaml](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/venues.yaml). Then the identifier would be:

    {venue_id}-{full_year}-{volume}.{paper_number}

e.g., [https://www.aclweb.org/anthology/wmt-2018-1.1](https://aclweb.org/anthology/W18-6301/) (which is currently W18-6301).

An advantage to this is that it would put down the occasional complaint of us assigning workshop IDs to what are actually fairly big conferences (e.g., AMTA, WMT, IWPT, Nordic Conference on CL, many others).

**Comment by mjpost** [comment]
Noting that currently, all W* events are listed as ACL events, but this is [not the case](https://docs.google.com/spreadsheets/d/166W-eIJX2rzCACbjpQYOaruJda7bTZrY7MBw_oa7B2E/edit#gid=0), since W prefixes are used as a catchall, for non-ACL events, too.

**Comment by nschneid** [comment]
Thinking in terms of citation managers, it would be nice to be able to sniff a part of a URL and determine whether it is a paper ID (including current ones). What about banning lowercase letters in paper IDs? AFAICT the current site URLs only use capital letters when identifying a paper ID (or the venue prefix used in IDs).

**Comment by knmnyn** [comment]
Yes, @nschneid that's correct.  The ACL Anthology ID currently consists only of capital letters to identify papers.

**Comment by mjpost** [comment]
When we move to the format suggested above, however, I imagine what we'll do is:

- Use lowercase letters for the venue id (e.g., `acl-2019-1.1` for the first paper in the first volume of ACL)
- Add new IDs for all papers in the Anthology, but maintain the existing IDs for papers before 2020

It seems like this is still an identifiable pattern, though, so this should not be a problem?

**Comment by nschneid** [comment]
The pattern for the old format is `[A-Z]\d{2}-\d{4}`. Would the new one be `[a-z]+-\d{4}-\d+\.\d+`? Or could the venue name contain `-`, `*`, `+`, digits, non-ASCII characters, ....

**Comment by mjpost** [comment]
I think we would require that venue identifiers be (a) unique and (b) contain ASCII letters and digits only. But the precise format and rules here are something I'd like more input on from the @acl-org/anthology team. We already have [a list of venue names](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/venues.yaml) and some of them won't fit within this format. Probably this is going to get complicated fast.

**Comment by mjpost** [comment]
Resolved with commit 2efedd841154d3c1dd8a66a4f5ec5536cf872a1e

**Comment by mjpost** [comment]
Picking this up again with a follow up question: We currently suggest that single-volume workshops name their volume "1", for lack of a better name, yielding for example `2020.mwe-1` as the volume name. What if we suggested workshop organizers instead use the volume name of the conference the workshop is associated with? For example, MWE this year is being held at COLING, so they would have `2020.mwe-coling` as their volume name.
