### ISSUE TITLE
INLG 2017 proceedings not listed for SIGGEN

### ISSUE THREAD

**Issue by evanmiltenburg** [acl-org/acl-anthology#41]
I know the INLG 2017 proceedings are in the anthology ([pdf](http://aclweb.org/anthology/W/W17/W17-35.pdf), [bib](http://aclweb.org/anthology/W/W17/W17-35.bib)), but they're not listed on the [SIGGEN page](https://aclanthology.coli.uni-saarland.de/sigs/siggen) and don't appear in the [search results](https://aclanthology.coli.uni-saarland.de/catalog?utf8=%E2%9C%93&search_field=all_fields&q=inlg).

**Comment by villalbamartin** [comment]
Bug caused by an incorrect installation procedure, which has been now fixed.

**Comment by villalbamartin** [comment]
Sorry, I accidentally selected the wrong option. I'm re-opening this one and assigning it to me.

**Comment by knmnyn** [comment]
SIG GEN page regenerated.  The indexing issues are a separate thing which I think Martín has already fixed.  Closing.

**Comment by evanmiltenburg** [comment]
The proceedings still don't show up on the new page, though. Compare:

* Old page does have it: http://aclweb.org/anthology/siggen.html
* New page doesn't https://aclanthology.coli.uni-saarland.de/sigs/siggen

**Comment by knmnyn** [comment]
This is a problem that was due to me.  I needed to bring over the new .yaml file for SIGGEN that was available and ingested for the legacy Anthology but not the current one.

**Comment by knmnyn** [comment]
Fixed by reimporting.  Close #41
