### ISSUE TITLE
Having added ORCIDs for previous years, some got assigned to the wrong people - bug or raw data problem?

### ISSUE THREAD

**Issue by weissenh** [acl-org/acl-anthology#6849]
I don't know whether this comes from the underlying raw data or some bug / mistake at ORCID ingestion.

**How I came across this problem**  
I've already reported three instances in https://github.com/acl-org/acl-anthology/issues/6810#issuecomment-3666750700  (after a first, for gozde-gul-sahin, has been found by @mbollmann in the same issue and mistakenly attributed to the metadata bulk processing reordering bug).

I've taken the people.yaml on master-new-author-system-ui branch and tried to find people whose name variants show non-overlapping names (e.g. "Alexander Fraser" and "Kristian Kersting" don't have overlapping name parts, but "John Doe" and "J. Doe" have). My ad-hoc script might be too simple to detect all instances, but it found about 20 instances (including the three already mentioned in the other issue). 
I've taken a closer look at half of the instances:
- quite often the two persons are co-authors on the same paper. However, this is not always the case, e.g. Joey Chuang with Hitomi Yanaka, Kentaro Yamada with Piyawat Lertvittayakumjorn. The second pair I noticed there is another ORCID that got misassigned on the same paper, but since the ORCID only appears once in our data, I have no way to detect it with a script that looks for different name variants for one ORCID...
- the wrong ORCIDs were introduced in several commits: "Added ORCID iDs for NAACL 2022", "Add ORCID iDs for ACL 2023", "Add 2024 ORCID iDs", "Add ORCIDs 2025", "Added orcid for EMNLP 2024"

**Size of the problem**
As said, I've found around 20 instances. However, my script isn't perfect in detecting non-overlapping names. 
But more importantly, I am only able to detect instances where the ORCID appears on more than one paper... If two affected authors only published one paper, detecting a wrong orcid-author mapping for these would be harder. 

**Effect**
With the new author representation :
- authors can have silly "name variants" (potentially those from co-authors)
- the wrong author is verified, and the right one doesn't have a page at all
- a verified author page will contain papers the author hasn't co-authored (e.g. 2025 paper for Kentaro Yamada in [UI preview](https://preview.aclanthology.org/master-new-author-system-ui/people/kentaro-yamada/)) 
- an author page can contain the same paper twice if the id is assigned to both a co-author and the author themself (e.g. Alice Oh the Kallm paper 2024) and clicking on the co-author name won't lead you to their site
- show ambiguity of author name when there is none (e.g. Hitomi Yanaka in [UI preview](https://preview.aclanthology.org/master-new-author-system-ui/people/hitomi-yanaka/))

**Suggestion**
- find and fix all wrong instances
- investigate whether this is a bug or a raw data problem: can we prevent this problem for future ingestions?

**Further comments**
PS: Independent of this or together with this, it would be interesting to explore whether there are papers where the same name or slug appears twice or the slug matches the name of some co-author...

Some examples:

<details>
<summary>Click on triangle to (un)collapse</summary>

Links on names point to orcid.org pages, showing which ORCiD is affected - the other name of the pair should not be associated with this ORCID  and respective slug *unless we would have evidence that the names do belong to the same person (like Hakaze Cho and Yufeng Zhao)*

- albert-lam: [Albert (Y.S.) Lam](https://orcid.org/0000-0002-6887-9301) / Xiao-Ming Wu: 
  - 2022.naacl-main.39 (co-authors)
  - 2023.findings-acl.706  (co-authors, swapped both orcids)
  - `git log -L 560,+5:'data/xml/2022.naacl.xml'`
  - `git log -L 12002,+5:'data/xml/2023.findings.xml'` 
- alice-oh: Alice Oh / [Seunghyun Yoon](https://orcid.org/0000-0002-7262-3579) : 
  - 2024.kallm-1.1 (co-authors)
  - `git log -L 28,+5:'data/xml/2024.kallm.xml'`
- amanda-cercas-curry: [Amanda Cercas Curry](https://orcid.org/0000-0002-8964-5790) / Benjamin Genchel:
  - 2025.naacl-long.617 (co-authors)
  - `git log -L 8451,+5:'data/xml/2025.naacl.xml'`
- dominik-beese: Dominik Beese / [Benjamin Paassen](https://orcid.org/0000-0002-3899-2450): 
  - 2024.emnlp-main.337 (co-authors)
  - `git log -L 4760,+5:'data/xml/2024.emnlp.xml'`
- manabu-okumura: [Manabu Okumura](https://orcid.org/0009-0001-7730-1536) / Hidetaka Kamigaito or hidetaka-kamigaito: [Hidetaka Kamigaito](https://orcid.org/0000-0002-5249-5813) / Jingun Kwon: 
  - 2024.findings-acl.532
  - co-authors, but wrong orcid-assignment on them
- traian-rebedea: [Traian Rebedea](https://orcid.org/0000-0002-7255-5537) / Makesh Sreedhar: 
  - 2024.findings-emnlp.713  (co-authors)
  - `git log -L 29195,+5:'data/xml/2024.findings.xml'`
- kentaro-yamada: Kentaro Yamada / [Piyawat Lertvittayakumjorn](https://orcid.org/0000-0002-2784-9827): 
  - 2024.acl-srw.26 : people are NOT co-authors, actually a second orcid (Hitomi Yanaka has orcid from [Peerapon Vateekul](https://orcid.org/0000-0001-9718-3592)) is wrong too but this was hard to detect as it only appears once. ORCIDs should go to 2024.acl-srw.19 instead
  - `git log -L 14022,+5:'data/xml/2024.acl.xml'`
- hitomi-yanaka: [Hitomi Yanaka](https://orcid.org/0000-0003-0354-6116) / Joey Chuang : 
  - 2024.acl-srw.34 (NOT co-authors)
  - `git log -L 14104,+2:'data/xml/2024.acl.xml'`

</details>

**Comment by nschneid** [comment]
#5708 tracks ingestion of ORCIDs for past venues

**Comment by mbollmann** [comment]
I think this is definitely a blocker for the transition.

What I probably would like to do at this point is to run a (one-off) script that checks each ORCID we have against the official ORCID records, to see if there’s a name match (or at least significant string overlap).

>   * an author page can contain the same paper twice if the id is assigned to both a co-author and the author themself (e.g. Alice Oh the Kallm paper 2024) and clicking on the co-author name won't lead you to their site

You mean that the same author ID is used twice on the same paper? This feels like something the library should flag as an error (but probably doesn’t yet), I can see if I can add that.

>   * investigate whether this is a bug or a raw data problem: can we prevent this problem for future ingestions?

This would be most relevant to find out, IMHO. @mjpost, maybe you can take some of the erroneous instances listed here and grep for them in the original ingestion data?

There’s also a non-zero chance that the transition script did something wrong. @weissenh, did you check (maybe on a few instances) if these errors already exist pre-transition (i.e. on the master branch)?

**Comment by weissenh** [comment]
Answering @mbollmann right before I sign off for today:

> You mean that the same author ID is used twice on the same paper? This feels like something the library should flag as an error (but probably doesn’t yet), I can see if I can add that.

Exactly. It's not like all of the above-mentioned examples had that, but I found two 
- 2024.findings-acl.532  id: manabu-okumura
- 2024.sighan-1.18  id: hongru-wang

> This would be most relevant to find out, IMHO. 

I don't have the time nor the data to check the raw data, so I cannot help with this sadly.
What I notice in the ingestion script is that there is a very basic check if names match, but only a message is printed for each case (match / no match), but the control flow is not changed to not execute the add orcid part if names don't match (cf. https://github.com/acl-org/acl-anthology/blob/e3104f16b77c6d27a9a146af3272d01f1b28a1c9/bin/ingest_orcids.py#L207 ). I don't know whether whoever executed the script went through the messages afterwards and manually reviewed the non-matching names messages/items. And I haven't checked what version of this script was used in the various ingestion commits my examples come from.

> @weissenh, did you check (maybe on a few instances) if these errors already exist pre-transition (i.e. on the master branch)?

I viewed the git log for the relevant XML lines (as documented above). It was not the transition script that introduced the wrong ORCIDs as far as I can tell, but the transition script then assigned the wrong id to keep it consistent with the wrong ORCID.

I did verify on the master branch again for the following examples:

Schema: (git log, orcid, name on orcid.org page, name in xml at the orcid-relevant position)
- git log -L 560,+5:'data/xml/2022.naacl.xml'  https://orcid.org/0000-0002-6887-9301 Albert (Y.S.) Lam / Xiao-Ming Wu
- git log -L 12002,+5:'data/xml/2023.findings.xml'  https://orcid.org/0000-0002-6887-9301 Albert (Y.S.) Lam / Xiao-Ming Wu
- git log -L 28,+5:'data/xml/2024.kallm.xml'  https://orcid.org/0000-0002-7262-3579  Seunghyun Yoon / Alice Oh 
- git log -L 8451,+5:'data/xml/2025.naacl.xml'  https://orcid.org/0000-0002-8964-5790   Amanda Cercas Curry / Benjamin Genchel
- git log -L 14104,+2:'data/xml/2024.acl.xml'  https://orcid.org/0000-0003-0354-6116  Hitomi Yanaka / Joey Chuang

**Comment by nschneid** [comment]
An author mismatch would occur if the author list was corrected in the XML between original ingestion time and ORCID ingestion time, yes?

> * git log -L 28,+5:'data/xml/2024.kallm.xml'  https://orcid.org/0000-0002-7262-3579  Seunghyun Yoon / Alice Oh

Git blame of the XML: https://github.com/acl-org/acl-anthology/blame/master/data/xml/2024.kallm.xml#L28

This shows that the authors were indeed reordered on Aug 15, 2024.

Presumably an error was printed by ingest_orcids.py. Rerunning that script could be a way to find the ORCIDs that need correcting.

**Comment by weissenh** [comment]
> An author mismatch would occur if the author list was corrected in the XML between original ingestion time and ORCID ingestion time, yes?

Good point! Yeah that could be it, mostly.

Here are two more examples of this kind with git blame and the commit I identified:
- 2022.naacl-main.39 for Albert Lam and Xiao-Ming Wu: [Git Blame on master 2022.naacl L560](https://github.com/acl-org/acl-anthology/blame/master/data/xml/2022.naacl.xml#L560) - author order was changed with Corrections September 2024 [see here](https://github.com/acl-org/acl-anthology/commit/7e6d1ace2ce07bbe5f9d71124c644ce9f9a1af1e#diff-ccc155a89f25f13d2bd91d5a3edb613f03a4d5801e444272ca73df1e6eb87a31R621)
- 2025.naacl-long.617 for Amanda Cercas Curry / Benjamin Genchel: [Git Blame on master 2025.naacl L8451](https://github.com/acl-org/acl-anthology/blame/master/data/xml/2025.naacl.xml#L8451) - Benjamin Genchel was added as an author with [corrections 2025-05-21](https://github.com/acl-org/acl-anthology/commit/8edc81ad4e525f1d15901b44f48b3ad14780f378) (2025.naacl.xml)

However, I've also reported instances where the seemingly incorrect ORCIDs were from non-co-authors. So aside from reordering of author order we maybe also need to consider changes in the paper list? 

Revisiting my examples with such a problem, I notice they stem from 2024.acl-srw. Now, I vaguely remember we have some open GitHub issues on 2024 ACL SRW papers taken down as non-archival - I don't know whether this is coincidence or related. 

Looking back at the script as it is currently, I notice it never checks explicitly, whether the author list from the raw data and the author list in the XML *actually belong to the same paper.* ... It only checks whether the author lists have the same length (though for the Benjamin Genchel addition example above, I don't know how that would fit). Of course, two different papers could have the same length (e.g. my non-co-author-examples above have three authors: 2024.acl-srw.26, 2024.acl-srw.19, 2024.acl-srw.34 ) and this potentially misses ingesting ORCIDs for papers where we deleted/added co-authors between original ingestion time and ORCID ingestion time.

> Presumably an error was printed by ingest_orcids.py. Rerunning that script could be a way to find the ORCIDs that need correcting.

Mhm yes, though I wonder about error rate in terms of false negatives and false positives of the name matching algorithm.
If the name matching is too permissive, we would not get a "no match" warning, but a "match" message hidden between many correct "match" messages (e.g. in case of single letter or zero letter last name in the raw data, seemingly matching end of author first/last name in XML data). Maybe the number of false "match" messages are negligible. In this case, the one-off check against the orcid.org page that Marcel suggested might save us.

**Comment by nschneid** [comment]
Can this be closed?

**Comment by mjpost** [comment]
I think so but will leave it to @weissenh as its opener.

**Comment by weissenh** [comment]
I've taken a look at the instances I identified and listed in the original issue description. I can confirm they are correct now on `master-new-author-system`.

I cannot guarantee we haven't missed any error introduced by the bug, but with the check you performed against orcid.org followed by deleting wrong assignments, it looks alright (the bug is still in the code though).
I've run `dump_orcid_info.py` on `master-new-author-system`and skimmed through the results. I did not spot any glaring incorrect ORCID assignments, though it is hard to tell for people with name set to private, only provided one name component on orcid.org, abbreviated names to initials etc.

So I will close this issue now.
We might choose to refer to this issue if we find further left-over effects of the bug.

PS: The changes haven't been merged into master-new-author-system-ui as of now, so the preview links I provided in the initial description still show the error.
